name: Deployment

# Trigger: Immer wenn auf den main-Branch gepusht wird
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Code aus dem Repo holen
      - name: Checkout Code
        uses: actions/checkout@v3

      # SSH-Agent starten und privaten Key laden
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

      # Deployment via SSH
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }},
          cd /home/christopher-schuf/Conduit-Deployment,
           docker compose pull,
           docker compose up -d --build